# fly.toml app configuration file generated for scm-frontend-1831 on 2023-06-16T18:31:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scm-frontend-1831"
primary_region = "ewr"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
