# fly.toml app configuration file generated for wild-mountain-6136 on 2023-06-15T14:26:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-mountain-6136"
primary_region = "ewr"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
