# fly.toml app configuration file generated for winter-dream-1988 on 2023-06-15T09:35:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winter-dream-1988"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
