[project]
name = "scm-backend"
version = "0.1.0"
description = "Add a short description here"
authors = ["John Dutchover <1983909-johndutchover@users.noreply.gitlab.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[tasks]
postinstall-e = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check ."
start-d =  { cmd = "python slackbolt_api.py" }
start =  { cmd = "python slackbolt_api.py", cwd = "backend" }

[dependencies]
python = ">3.10,<=3.12"
anyio = ">=3.7.1,<3.8"
fastapi = ">=0.110.0,<0.111"
slack-bolt = ">=1.18.1,<1.19"
pydantic = ">=2.6.3,<2.7"
uvicorn = ">=0.27.1,<0.28"
requests = ">=2.31.0,<2.32"
numpy = ">=1.26.4,<1.27"
motor = ">=3.3.2,<3.4"
dnspython = ">=2.6.1,<2.7"
aiohttp = ">=3.9.3,<3.10"
typing-extensions = ">=4.10.0,<4.11"
watchdog = ">=4.0.0,<4.1"
pytest-md = ">=0.2.0,<0.3"
pytest = ">=8.0.2,<8.1"
pytest-mock = ">=3.12.0,<3.13"

[host-dependencies]
python = "*"
pip = "*"

[feature.test.dependencies]
pytest = "*"
pytest-md = "*"
pytest-asyncio = "*"
typer = ">=0.9.0"
flake8 = ">=6.0.0"
black = ">=23.3.0"
pylint = ">=2.17.4"
gitpython = ">=3.1.35"
packaging = ">=22.0"

[feature.test.tasks]
test = "pytest --md=report.md"

[environments]
default = {features = ["test"], solve-group = "prod-group"}
prod = {features = [], solve-group = "prod-group"}

[pypi-dependencies]
load-dotenv = "*"
