# fly.toml app configuration file generated for dawn-violet-870 on 2023-06-13T19:24:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dawn-violet-870"
primary_region = "ewr"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
