# fly.toml app configuration file generated for shortcircuitme-backend on 2023-06-23T22:00:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shortcircuitme-backend"
primary_region = "ewr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
