name: Code Quality

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ prod ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.15.2
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: pixi run test
